config/routes.rb
Rails.application.routes.draw do
  devise_scope :customer do
    # Redirests signing out users back to sign-in
    get "customers", to: "devise/sessions#new"
  end
  
  devise_for :customers, path: ''

  devise_scope :user do
    # Redirests signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
  
  devise_for :users, path: 'admin/', controllers: { registrations: "registrations" }

  get 'contact', to: 'messages#new'
  get '/messages/confirmation', to: 'messages#confirmation'
  resources :messages

  get 'client-websites', to: 'pages#client_websites'
  get 'example-sites', to: 'pages#example_sites'
  get 'projects', to: 'pages#projects'
  get 'articles', to: 'pages#articles'
  resources :pages
  #get "/pages", to: "pages#index"
  #get "/pages/new", to: "pages#new"
  #get "/pages/:id", to: "pages#show"
  #post "/pages", to: "pages#create"  # usually a submitted form
  #get "/pages/:id/edit", to: "pages#edit"
  #put "/pages/:id", to: "pages#update" # usually a submitted form
  #delete "/pages/:id", to: "pages#destroy"

  root "home#index"

  
end

app/models/message.rb
class Message < ApplicationRecord
  validates :name, presence: true
  validates :content, presence: true
  validates :email, presence: true
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:new, :create, :confirmation]

  # GET /messages or /messages.json
  def index
    @messages = Message.all
  end

  def confirmation
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)
    
    validation_text = @message.validation_text.downcase
    #key = message_params[:key]
    #selected_hash = helpers.sentence_storage(key)

    if validation_text == helpers.answer_check(@message.key)
      respond_to do |format|
        if @message.save
          MessageMailer.new_message(@message).deliver
          format.html { redirect_to messages_confirmation_path, notice: @message.content}
          format.json { render :show, status: :created, location: @message }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @message.errors, status: :unprocessable_entity }
        end
      end

    else  
      respond_to do |format|
        format.html { redirect_to new_message_path, alert: "Error: You did not complete the sentence correctly" }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to message_url(@message), notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:name, :email, :content, :validation_text, :key)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_with(model: message, class: "contents") do |form| %>
  <%# FOR FORM VALIDATION %>
  <% keygen = random_number %>

  <%# FOR ERRORS %>
  <div class="px-10">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg h-full" id="notice"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg h-full" id="alert"><%= alert %></p>
    <% end %>
  </div>
  <% if message.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 mx-10 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being sent:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <!--Container for fields/button-->
  <div class="px-10 pb-10">
    <div class="my-5">
      <%= form.label :name %>
      <%= form.text_field :name, placeholder: "Your name", class: "placeholder-gray-300 block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full focus:border-red-800 focus:ring-red-800" %>
    </div>

    <div class="my-5">
      <%= form.label :email %>
      <%= form.email_field :email, placeholder: "Your email", class: "placeholder-gray-300 block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full focus:border-red-800 focus:ring-red-800" %>
    </div>

    <div class="my-5">
      <%= form.label "How can we help?" %>
      <%= form.text_area :content, placeholder: "Your message", rows: 4, class: "placeholder-gray-300 block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full focus:border-red-800 focus:ring-red-800" %>
    </div>

    <%# FORM VALIDATION%>
    <div class="my-5">
      <div>
        Prove you're human and complete the sentence:
      </div>
      <div class="text-sm italic text-gray-500">
        <%= sentence_generator(keygen) %>
      </div>
      <%= form.text_field :validation_text, placeholder: "Your answer", class: "placeholder-gray-300 block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full focus:border-red-800 focus:ring-red-800" %>
      <%= form.hidden_field :key, :value => keygen  %>
    </div>  

    <div class="inline">
      <%= form.submit "Send", class: "rounded-lg py-3 px-5 w-full bg-red-800 text-white inline-block font-medium cursor-pointer hover:bg-red-700 active:bg-red-600" %>
    </div>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div id="<%= dom_id message %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= message.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= message.email %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Content:</strong>
    <%= message.content %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this message", message, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this message', edit_message_path(message), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/messages/confirmation.html.erb
<main class="bg-zinc-50 w-full flex flex-col items-center justify-center">
  <!--Container for contents-->
  <div class="text-center lg:w-3/5 md:w-4/5">
    
    <h1 class="font-bold text-4xl py-10">Your message has been sent!</h1>
    
    <!--Container for check-->
    <div class="flex flex-row justify-center">
      <!--circle of check-->
      <div class="bg-green-300 rounded-full py-3 px-4 mb-10">
        <!--check itself-->
        <div class="text-green-500 text-5xl">✓</div>
      </div>
    </div>
    
    
    <%#-- The message (lol, i used a "notice" to bring the message data to this page hahahaha) --%>
    <% if notice.present?%>
    <p class="font-semibold">Your Message:</p>
    <div class="mb-5 px-5 italic text-gray-500 text-sm">
      <%= notice %>
      </div>
    <% end %>
  
    
    <p class="px-5">
    Thank you for contacting Tim Jedrek LLC.  We are looking forward to working with you soon.  We will review your message and get back with you within 1-5 business days.  <br><br>
    You can also give us a call at 1-314-358-2100 or email us at <%= mail_to 'support@timjedrek.com', class: "text-red-800 hover:underline"%>
    </p>

    <div class="pt-10 flex flex-row justify-center">
    <%= link_to root_path do %>
      <div class="rounded-lg bg-red-800 hover:bg-red-700 active:bg-red-600 text-white py-3 px-32 mb-10">
        Home
      </div>
    <% end %>
    </div>
    

    <%#= link_to 'Back to messages', messages_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</main>

app/views/messages/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing message</h1>

  <%= render "form", message: @message %>

  <%= link_to "Show this message", @message, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to messages", messages_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/messages/index.html.erb
<main class="bg-zinc-50 w-full">
<h1 class="text-4xl font-bold text-center py-10">Messages</h1>

<% @messages.order(:created_at).reverse_each do | message | %>
  <div class="border-2 my-3 mx-3 p-3 bg-white rounded-xl">
    <div class="flex flex-row">
      <div class="flex flex-row">
        <div class="flex flex-col text-sm">
          <div class="flex flex-row">
            <div class="font-bold">ID</div>: <%= message.id %>
          </div>
          <div class="flex flex-row">
            <div class="font-bold">Name</div>: <%= message.name %>
          </div>
          <div class="flex flex-row">
            <div class="font-bold">Date</div>: <%= message.created_at.strftime("%b %e, %Y")%>
          </div>
          <div class="flex flex-row">
            <div class="font-bold">Email</div>: <%= message.email %>
          </div>
        </div>
      </div>
    </div>
    <hr class="my-2">
    <%= message.content %>
  </div>
<% end %>
</main>

app/views/messages/new.html.erb
<main class="bg-zinc-50 w-full flex flex-col items-center justify-center">
  <!--Container for contents-->
  <div class="lg:w-3/5 md:w-4/5">
    <h1 class="font-bold text-4xl text-center pt-10">Let's get started!</h1>
    <div class="italic text-gray-500 text-sm text-center pt-3 pb-10 px-10">Fill out the form below and we will get back with you shortly.  You can also give us ring at <span class="text-red-800 hover:underline">1-314-358-2100</span> or email us at <%= mail_to "support@timjedrek.com", class: "text-red-800 hover:underline" %>.  We're looking forward to meeting with you soon!</div>
    <%= render "form", message: @message %>

    <%#= link_to 'Back to messages', messages_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</main>

app/views/messages/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @message %>

    <%= link_to 'Edit this message', edit_message_path(@message), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this message', message_path(@message), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to messages', messages_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>