config/routes.rb
Rails.application.routes.draw do
  devise_scope :customer do
    # Redirests signing out users back to sign-in
    get "customers", to: "devise/sessions#new"
  end
  
  devise_for :customers, path: ''

  devise_scope :user do
    # Redirests signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
  
  devise_for :users, path: 'admin/', controllers: { registrations: "registrations" }

  get 'contact', to: 'messages#new'
  get '/messages/confirmation', to: 'messages#confirmation'
  resources :messages

  get 'client-websites', to: 'pages#client_websites'
  get 'example-sites', to: 'pages#example_sites'
  get 'projects', to: 'pages#projects'
  get 'articles', to: 'pages#articles'
  resources :pages
  #get "/pages", to: "pages#index"
  #get "/pages/new", to: "pages#new"
  #get "/pages/:id", to: "pages#show"
  #post "/pages", to: "pages#create"  # usually a submitted form
  #get "/pages/:id/edit", to: "pages#edit"
  #put "/pages/:id", to: "pages#update" # usually a submitted form
  #delete "/pages/:id", to: "pages#destroy"

  root "home#index"

  
end

app/views/shared/_copyright.html.erb
<p class="text-white text-center pt-10">
  Copyright <%= Date.today.year %> Tim Jedrek LLC
</p>

app/views/shared/_customer_menu.html.erb
<div x-data="{ usermenu: false }" class="">
  <div class="w-full h-16 bg-slate-900 flex flex-row justify-between items-center">
    <div class="pl-10 text-slate-100">
      Welcome, <%= current_customer.email %>
    </div>

    <!--Hamburger button-->
    <button @click="usermenu = ! usermenu;" class="text-slate-500 text-4xl pr-5 pb-1 hover:text-slate-700 lg:hidden">
      ☰
    </button >
    
    <!--desktop menu-->
    <div class="hidden lg:block lg:flex lg:flex-row lg:pr-10 xl:pr-5">
      <!--Button-->
      <%= button_to 'Dashboard', root_path, method: :get, class: "text-center block p-3 px-6 mr-5 text-slate-900 bg-slate-300 rounded-lg hover:bg-slate-400" %>
      <%= button_to 'Payment', root_path, method: :get, class: "text-center block p-3 px-6 mr-5 text-slate-900 bg-slate-300 rounded-lg hover:bg-slate-400" %>
      <%= button_to 'Account History', root_path, method: :get, class: "text-center block p-3 px-6 mr-5 text-slate-900 bg-slate-300 rounded-lg hover:bg-slate-400" %>
      <%= button_to 'Edit Profile', edit_customer_registration_path, method: :get, class: "text-center block p-3 px-6 mr-5 text-slate-900 bg-slate-300 rounded-lg hover:bg-slate-400" %>
      <%= button_to 'Sign Out', destroy_customer_session_path, method: :delete, class: "text-center block p-3 px-6 mr-5 text-slate-900 bg-slate-300 rounded-lg hover:bg-slate-400" %>
    </div>
  </div>

    <!--Mobile Menu--->
    <div x-show="usermenu" x-transition.duration.200ms class="bg-slate-900 flex flex-col justify-start items-center pb-10">
      <%= button_to 'Dashboard', root_path, method: :get, class: "text-center text-slate-100 hover:text-slate-400 leading-10" %>
      <%= button_to 'Payment', root_path, method: :get, class: "text-center text-slate-100 hover:text-slate-400 leading-10" %>
      <%= button_to 'Account History', root_path, method: :get, class: "text-center text-slate-100 hover:text-slate-400 leading-10" %>
      <%= button_to 'Edit Profile', edit_customer_registration_path, method: :get, class: "text-center text-slate-100 hover:text-slate-400 leading-10" %>
      <%= button_to 'Sign Out', destroy_customer_session_path, method: :delete, class: "text-center text-slate-100 hover:text-slate-400 leading-10" %>

    <!--Close button-->
    <button @click="usermenu = ! usermenu;" class="leading-10 text-slate-100 hover:text-slate-400 border-2 hover:border-slate-400 w-min mt-5 px-5 rounded-full py-1">
      X
    </button>

    </div>
  </div>

app/views/shared/_footer.html.erb
<footer class="bg-red-800 lg:hidden">
  <div class="py-10 flex flex-col items-center">
    <%= render "shared/nav_bottom"%>
  </div>
</footer>

app/views/shared/_logo.html.erb
<div class="flex flex-row justify-center items-center">
  <%= link_to root_path do %>
    <%= image_tag 'main/logo-timjedrek' , class: "lg:w-min" %>
  <% end %>
</div>

app/views/shared/_mobile_menu.html.erb
<div x-data="{ open: false }" class="pb-2 text-center items-center text-white flex flex-col fixed bg-red-800 w-full left-0 drop-shadow-2xl z-50">
  <div class="flex flex-row items-center justify-between w-full py-3">
    <!--Logo-->
    <div class="ml-3">
      <%= render "shared/logo" %>
    </div>
    <!--Hamburger button-->
      <button x-ref="hardware" @click="open = ! open" class="text-4xl text-red-400 hover:text-red-500 mr-3">
        ☰
      </button>
  </div>

  <!--Container for mobile menu-->
  <div x-show="open" x-transition.duration.200ms class="flex flex-col items-center justify-center mt-24 pb-32 fixed bg-red-800 w-screen h-screen z-50">
    <!--links-->
    <ul class="text-md">
      <li><%= link_to "Home", root_path, class: "leading-10 hover:text-red-400" %></li>
      <li><%= link_to "Client Websites", client_websites_path, class: "leading-10 hover:text-red-400" %></li>
      <li><%= link_to "Projects", projects_path, class: "leading-10 hover:text-red-400" %></li>
      <li><%= link_to "Articles", articles_path, class: "leading-10 hover:text-red-400" %></li>
      <li><%= link_to "Contact", contact_path, class: "leading-10 hover:text-red-400" %></li>
    </ul>
    <!--Close button-->
    <button @click="open = ! open; $refs.hardware.style.display='block'" x-transition.duration.200ms class="leading-10 border-2 w-min mt-5 px-5 rounded-full py-1 hover:text-red-400 hover:border-red-400 ">
      X
    </button>
  </div>
</div>
<div class="h-24">
</div>

app/views/shared/_nav.html.erb
<nav class="flex flex-col items-center bg-red-800 lg:flex-auto lg:w-5/12 lg:justify-between">
  <% if current_page?(root_url)  %>
  <!--ONLY FOR HOME PAGE-->
    <!--top part-->
    <div class="flex flex-col items-center">
      <!--Container for Profile pic-->
      <div class="pt-16 px-10 pb-10">
        <%= image_tag 'profilepic2.jpg' , class: "w-72 rounded-full border-8" %>
      </div>

      <!--Container for logo-->
      <%= render "shared/logo" %>

      <!--Container for words and stuff-->
      <div class="flex flex-col items-center px-6">
        <!--Small blurb about us-->
        <p class="text-gray-300 py-10 text-center text-sm"> 
        Helping businesses grow <br>through software on the internet
        </p>
        <!--Links-->
        <%= render "shared/top_links"%>
      </div>
    </div>
  <% else %>
  <!--FOR ALL OTHER PAGES-->
    <!--top part-->
    <div class="flex flex-col items-center">
      <!--Container for Profile pic-->
      <div class="hidden lg:block pt-16 px-10 pb-10">
        <%= image_tag 'profilepic2.jpg' , class: "w-72 rounded-full border-8" %>
      </div>

      <!--Container for logo-->
      <div class="hidden lg:flex flex-col items-center">
        <%= render "shared/logo" %>
      </div>

      <!--Container for words and stuff-->
      <div class="hidden lg:flex flex-col items-center px-6">
        <!--Small blurb about us-->
        <p class="hidden lg:block text-gray-300 py-10 text-center text-sm"> 
        A web development venture assisting small to medium sized businesses grow through website and software solutions.
        </p>
        <!--Links-->
        <div class="hidden lg:block">
          <%= render "shared/top_links"%>
        </div>
      </div>

      <!--Mobile menu-->
      <div class="lg:hidden">
        <%= render "shared/mobile_menu"%>
      </div>
    </div>  
    <% end %>
    
    <!--bottom part-->
    <div class="pb-10 flex-col items-center hidden lg:flex">
      <%= render "shared/nav_bottom"%>
    </div>
  
</nav>

app/views/shared/_nav_bottom.html.erb
<% if current_page?(root_url) %>
<!--ONLY FOR HOME PAGE-->
  <!--Social media Icons-->
  <%= render "shared/social_media_icons"%>
  <!--Copyright-->
  <%= render "shared/copyright" %>

<% else %>
<!--FOR ALL OTHER PAGES-->
  <!--Social media Icons-->
  <%= render "shared/social_media_icons"%>
  <!--Copyright-->
  <%= render "shared/copyright" %>
<% end %>

app/views/shared/_social_media_icons.html.erb
<p class="flex flex-row justify-center gap-6">
<%= link_to "https://www.linkedin.com/in/tim-santos/" do%>
  <%= image_tag 'icons/linkedin' , class: "h-10 hover:brightness-125"%>
<% end %>
<%= link_to "https://github.com/timjedrek" do %>
  <%= image_tag 'icons/github' , class: "h-10 hover:brightness-125"%>
<% end %>
<!-- Add youtube? -->
</p>

app/views/shared/_top_links.html.erb
  <p class="flex flex-col gap-5 text-white text-center pb-10 lg:pb-20">
  <%= link_to "Home", root_path, class: "hover:text-red-400" %>
  <%= link_to "Client Websites", client_websites_path, class: "hover:text-red-400" %>
  <%= link_to "Projects", projects_path, class: "hover:text-red-400" %>
  <%= link_to "Articles", articles_path, class: "hover:text-red-400" %> 
  <%= link_to "Contact", contact_path, class: "hover:text-red-400" %>
  </p>

app/views/shared/_user_menu.html.erb
<div x-data="{ usermenu: false }" class="">
  <div class="w-full h-16 bg-stone-700 flex flex-row justify-between items-center">
    <div class="pl-10 text-stone-100">
      Welcome, <%= current_user.email %>
    </div>

    <!--Hamburger button-->
    <button @click="usermenu = ! usermenu;" class="text-stone-500 text-4xl pr-5 pb-1 hover:text-stone-800 lg:hidden">
      ☰
    </button >
    
    <!--desktop menu-->
    <div class="hidden lg:block lg:flex lg:flex-row lg:pr-10 xl:pr-5">
      <!--Button-->
      <%= button_to 'Dashboard', messages_path, method: :get, class: "text-center block p-3 px-6 mr-5 text-stone-900 bg-stone-200 rounded-lg hover:bg-stone-300" %>
      <%= button_to 'Invoices', messages_path, method: :get, class: "text-center block p-3 px-6 mr-5 text-stone-900 bg-stone-200 rounded-lg hover:bg-stone-300" %>
      <%= button_to 'Customers', messages_path, method: :get, class: "text-center block p-3 px-6 mr-5 text-stone-900 bg-stone-200 rounded-lg hover:bg-stone-300" %>
      <%= button_to 'New Page', new_page_path, method: :get, class: "text-center block p-3 px-6 mr-5 text-stone-900 bg-stone-200 rounded-lg hover:bg-stone-300" %>
      <%= button_to 'Messages', messages_path, method: :get, class: "text-center block p-3 px-6 mr-5 text-stone-900 bg-stone-200 rounded-lg hover:bg-stone-300" %>
      <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: "text-center block p-3 px-6 mr-5 text-stone-900 bg-stone-200 rounded-lg hover:bg-stone-300" %>
    </div>
  </div>

    <!--Mobile Menu--->
    <div x-show="usermenu" x-transition.duration.200ms class="bg-stone-700 flex flex-col justify-start items-center pb-10">
      <%= button_to 'Dashboard', messages_path, method: :get, class: "text-center text-stone-100 hover:text-stone-400 leading-10" %>
      <%= button_to 'Invoices', messages_path, method: :get, class: "text-center text-stone-100 hover:text-stone-400 leading-10" %>
      <%= button_to 'Customers', messages_path, method: :get, class: "text-center text-stone-100 hover:text-stone-400 leading-10" %>
      <%= button_to 'New Page', new_page_path, method: :get, class: "text-center text-stone-100 hover:text-stone-400 leading-10" %>
      <%= button_to 'Messages', messages_path, method: :get, class: "text-center text-stone-100 hover:text-stone-400 leading-10" %>
      <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: "text-center text-stone-100 hover:text-stone-400 leading-10" %>

    <!--Close button-->
    <button @click="usermenu = ! usermenu;" class="leading-10 text-stone-100 hover:text-stone-400 hover:bg-stone-700 border-2 hover:border-stone-400 w-min mt-5 px-5 rounded-full py-1">
      X
    </button>

    </div>
  </div>