config/routes.rb
Rails.application.routes.draw do
  devise_scope :customer do
    # Redirests signing out users back to sign-in
    get "customers", to: "devise/sessions#new"
  end
  
  devise_for :customers, path: ''

  devise_scope :user do
    # Redirests signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
  
  devise_for :users, path: 'admin/', controllers: { registrations: "registrations" }

  get 'contact', to: 'messages#new'
  get '/messages/confirmation', to: 'messages#confirmation'
  resources :messages

  get 'client-websites', to: 'pages#client_websites'
  get 'example-sites', to: 'pages#example_sites'
  get 'projects', to: 'pages#projects'
  get 'articles', to: 'pages#articles'
  resources :pages
  #get "/pages", to: "pages#index"
  #get "/pages/new", to: "pages#new"
  #get "/pages/:id", to: "pages#show"
  #post "/pages", to: "pages#create"  # usually a submitted form
  #get "/pages/:id/edit", to: "pages#edit"
  #put "/pages/:id", to: "pages#update" # usually a submitted form
  #delete "/pages/:id", to: "pages#destroy"

  root "home#index"

  
end

app/views/pages/_feed_for_pages.html.erb
<div class="bg-zinc-50 w-full">
  <div class="m-10">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-100 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    
    <!--Header-->
    <div class="mt-10">
      <% if current_page?(client_websites_path) %>
        <h1 class="text-4xl font-bold pb-5">Client Websites</h1>
      <% end %>
      <% if current_page?(example_sites_path) %>
        <h1 class="text-4xl font-bold pb-5">Example Sites</h1>
      <% end %>
      <% if current_page?(projects_path) %>
        <h1 class="text-4xl font-bold pb-5">Projects</h1>
      <% end %>
      <% if current_page?(articles_path) %>
        <h1 class="text-4xl font-bold pb-5">Articles</h1>
      <% end %>
    </div>

    <!--Feed of all the pages-->
    <% @pages.order(:date).reverse_each do | page | %>
      <%= link_to page do %>
        <div class="py-5">
          <h2 class="text-lg font-bold"><%= page.title %></h2>
          <p class="text-gray-500">Created on: <%= page.date.strftime("%B %e, %Y") %></p>
          <p class="text-sm text-gray-500" ><%= page.body.to_plain_text.truncate(90) %></p>
        </div>
      <% end %>
    <% end %>
    

  </div>
</div>

app/views/pages/_form.html.erb
<%= form_with(model: page, class: "contents") do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full focus:border-red-800 focus:ring-red-800" %>
  </div>

  <div class="my-5">
    <%= form.label :date %>
    <%= form.date_field :date, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full focus:border-red-800 focus:ring-red-800" %>
  </div>

<div class="my-5">
    <%= form.label :category %>
    <%= form.select(:category, ['Client Websites','Example Sites','Projects','Articles'], {}, {:class => 'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full focus:border-red-800 focus:ring-red-800'}) %>
  </div>

  <div class="my-5">
    <%= form.label :body %>
    <%= form.rich_text_area :body, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full focus:border-red-800 focus:ring-red-800" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-red-800 text-white inline-block font-medium cursor-pointer hover:bg-red-700" %>
  </div>
<% end %>

app/views/pages/_page.html.erb
<div id="<%= dom_id page %>">

  <p class="text-4xl font-bold">
    <%= page.title %>
  </p>

  <p class="text-gray-500">
    <%= page.date.strftime("%B %e, %Y") %>
  </p>

  <% if user_signed_in? %>
    <p class="text-gray-500">
      Category: <%= page.category %>
    </p>
    <div class="pb-5 flex flex-row text-gray-500 gap-3">
      <%= link_to "Edit #{page.title}", edit_page_path(page), class: "hover:text-red-800" %> | 
      <%= button_to "Delete #{page.title}", page_path(page), method: :delete, class: "hover:text-red-800" %>
    </div>
  <% end %>

  <p class="my-5">
    <%= page.body %>
  </p>
</div>

app/views/pages/articles.html.erb
<%= render "feed_for_pages" %>

app/views/pages/client_websites.html.erb
<%= render "feed_for_pages" %>

app/views/pages/edit.html.erb
<div class="bg-zinc-50 w-full">
  <div class="m-10">
    <h1 class="font-bold text-4xl">Editing page</h1>

    <%= render "form", page: @page %>

    <%= link_to "Show this page", @page, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 hover:bg-gray-200 inline-block font-medium" %>
  </div>
</div>

app/views/pages/example_sites.html.erb
<%= render "feed_for_pages" %>

app/views/pages/home.html.erb
<!--Full Page container-->
<div class="flex flex-col lg:flex-row ">
  <!--First section / left section on desktop (navigation) -->
  <%= render "nav" %>

  <!--Main content stuff-->
  <%= render "main" %>

  <!--Footer (mobile only-->
  <%= render "footer" %>
</div>

app/views/pages/index.html.erb
<div class="bg-zinc-50 w-full">
  <div class="m-10">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-100 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <div id="pages" class="min-w-full">
      <%= render @pages %>
    </div>
  </div>
</div>

app/views/pages/new.html.erb
<div class="bg-zinc-50 w-full">
  <div class="m-10">
    <h1 class="font-bold text-4xl">New page</h1>

    <%= render "form", page: @page %>

    <%#= link_to 'Back to pages', pages_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/pages/projects.html.erb
<%= render "feed_for_pages" %>

app/views/pages/show.html.erb
<div class="bg-zinc-50 w-full">
  <div class="p-10">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-200 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @page %>

    <!--Back Link-->
    <div class="mt-10">
      <% if @page.category == "Client Websites" %>
        <%= link_to '↩ Back to Client Websites', client_websites_path, class: "text-red-800 hover:underline" %>
      <% end %>
      <% if @page.category == "Example Sites" %>
        <%= link_to '↩ Back to Example Sites', example_sites_path, class: "text-red-800 hover:underline" %>
      <% end %>
      <% if @page.category == "Projects" %>
        <%= link_to '↩ Back to Projects', projects_path, class: "text-red-800 hover:underline" %>
      <% end %>
      <% if @page.category == "Articles" %>
        <%= link_to '↩ Back to Articles', articles_path, class: "text-red-800 hover:underline" %>
      <% end %>
    </div>

    <%#= link_to 'Edit this page', edit_page_path(@page), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%#= button_to 'Destroy this page', page_path(@page), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    <%#= link_to 'Back to pages', pages_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>