config/routes.rb
Rails.application.routes.draw do
  devise_scope :customer do
    # Redirests signing out users back to sign-in
    get "customers", to: "devise/sessions#new"
  end
  
  devise_for :customers, path: ''

  devise_scope :user do
    # Redirests signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
  
  devise_for :users, path: 'admin/', controllers: { registrations: "registrations" }

  get 'contact', to: 'messages#new'
  get '/messages/confirmation', to: 'messages#confirmation'
  resources :messages

  get 'client-websites', to: 'pages#client_websites'
  get 'example-sites', to: 'pages#example_sites'
  get 'projects', to: 'pages#projects'
  get 'articles', to: 'pages#articles'
  resources :pages
  #get "/pages", to: "pages#index"
  #get "/pages/new", to: "pages#new"
  #get "/pages/:id", to: "pages#show"
  #post "/pages", to: "pages#create"  # usually a submitted form
  #get "/pages/:id/edit", to: "pages#edit"
  #put "/pages/:id", to: "pages#update" # usually a submitted form
  #delete "/pages/:id", to: "pages#destroy"

  root "home#index"

  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tim Jedrek - <%= random_title_text %></title>
    <!-- WELCOME TO THE HOMEPAGE OF
    
         _____ _            _        _         _   
        |_   _(_)_ __    _ | |___ __| |_ _ ___| |__
          | | | | '  \  | || / -_) _` | '_/ -_) / /
          |_| |_|_|_|_|  \__/\___\__,_|_| \___|_\_\


    Nice to see you here.  Choose Tim Jedrek for all of your IT needs.  https://timjedrek.com/contact -->

    <!--Meta Tags-->
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="title" content="Tim Jedrek - Website Design, E-Commerce, Enterprise Software">
    <meta name="description" content="A web development venture assisting small to medium sized businesses grow through website and software solutions.">
    <meta name="keywords" content="website, site, designer, maker, editor, WordPress, Wix, Square, Shopify, template, theme, e-commerce, sell, online, free, products, sales, marketing, St. Louis, Missouri, mobile, app, management, business, system, database, log, dashboard, records, invoice, accounting, talent, lifecycle, audit, quality, register, automate, automation, operation, HR, finance, cost, SEO">
    <meta name="robots" content="index, follow">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="language" content="English">
    <meta name="revisit-after" content="1 days">
    <meta name="author" content="Me">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://timjedrek.com">
    <meta property="og:title" content="Tim Jedrek - Website Design, E-Commerce, Enterprise Software">
    <meta property="og:description" content="A web development venture assisting small to medium sized businesses grow through website and software solutions.">
    <meta property="og:image" content="<%= image_url('timjedrek.png') %>">

    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:url" content="https://timjedrek.com">
    <meta property="twitter:title" content="Tim Jedrek - Website Design, E-Commerce, Enterprise Software">
    <meta property="twitter:description" content="A web development venture assisting small to medium sized businesses grow through website and software solutions.">
    <meta property="twitter:image" content="<%= image_url('timjedrek.png') %>">

    <!--Favicon--> 
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <% %w(57 72 76 114 120 144 152 180).each do |size| %>
      <%= favicon_link_tag "apple-touch-icon-#{size}x#{size}.png", rel: 'apple-touch-icon', type: 'image/png', sizes: "#{size}x#{size}" %>
    <% end %>

    <!--CSS-->
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    
    <!--JS-->
    <%= javascript_importmap_tags %>
    <script defer src="https://unpkg.com/alpinejs@3.10.3/dist/cdn.min.js"></script>
  </head>

  <!-- Google tag (gtag.js) / Google Analytics-->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-BX9M6HDXXQ"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-BX9M6HDXXQ');
  </script>

  <body class="bg-red-800">
    <% if user_signed_in? %>
      <!--USER MENU-->
      <%= render "shared/user_menu" %>
    <% end %>

    <% if customer_signed_in? %>
      <!--CUSTOMER MENU-->
      <%= render "shared/customer_menu" %>
    <% end %>

    <!--Full Page container-->
    <div class="flex flex-col lg:flex-row">
      <!--First section / left section on desktop (navigation) -->
      <%= render "shared/nav" %>

      <!--Yield-->
      <%= yield %>

      <!--Footer (mobile only)-->
      <%= render "shared/footer" %>
    </div>
  </body>
</html>